services:
    flaskapi-guard-example:
      build:
        context: .
        args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
      image: flaskapi-guard-example-py${PYTHON_VERSION:-3.10}
      command: gunicorn examples.main:app --bind 0.0.0.0:8000 --reload
      ports:
        - "8000:8000"
      environment:
        - REDIS_URL=redis://redis:6379
        - REDIS_PREFIX=${REDIS_PREFIX:-"flaskapi_guard:"}
        - IPINFO_TOKEN=${IPINFO_TOKEN:-"test_token"}
      volumes:
        - ./examples:/app/examples:z
        - ./flaskapi_guard:/app/flaskapi_guard:z
      depends_on:
        redis:
          condition: service_started

    flaskapi-guard:
      build:
        context: .
        args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
      image: flaskapi-guard-py${PYTHON_VERSION:-3.10}
      command: pytest -v --cov=.
      environment:
        - REDIS_URL=redis://redis:6379
        - REDIS_PREFIX=${REDIS_PREFIX:-"test:flaskapi_guard:"}
        - IPINFO_TOKEN=${IPINFO_TOKEN:-"test_token"}
      volumes:
        - ./flaskapi_guard:/app/flaskapi_guard:z
        - ./tests:/app/tests:z
        - ./pyproject.toml:/app/pyproject.toml:z
        - ./uv.lock:/app/uv.lock:z
        - ./vulture_whitelist.py:/app/vulture_whitelist.py:z
      depends_on:
        redis:
          condition: service_started

    redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data:
